### ISSUE TITLE
Python 3.8 Additional Dependencies

### ISSUE THREAD

**Issue by jrmcgaha-dev** [INTERSECT-SDK/python-sdk#10]
Bug: Failure to import on Python 3.8.19 even though Python 3.8.10 is listed as supported in the environment.yaml.

Reproduction steps:
1. Create python 3.8 environment
2. `python -m pip install intersect-sdk`
3. `python`
4. `import intersect_sdk`

This can be solved by instead doing `python -m pip install intersect-sdk[py38]`; however this solution requires a user perusing the environment.yaml themselves. A better long-term solution may be to add an appropriate conditional dependency of `eval-type-backport`.

Recommended fix: Add `"eval-type-backport>=0.1.3;python_version<'3.10'"` to dependencies and remove the separate `py38` optional dependency.

Edit: Getting reports this is a problem for 3.9 also, so adjusting recommended solution to account for this.

**Comment by wigging** [comment]
This also occurs with Python 3.9. The type hints used in the sdk seem to be for Python 3.10 and higher.

**Comment by Lance-Drane** [comment]
should be resolved in https://github.com/INTERSECT-SDK/python-sdk/pull/11
