### ISSUE TITLE
IntersectDirectMessageParams Name Change Documentation

### ISSUE THREAD

**Issue by jrmcgaha-dev** [INTERSECT-SDK/python-sdk#18]
On attempting to upgrade from 0.6.4 to 0.8.0, I noticed an unexpected failing import on `IntersectClientMessageParams`.

This appears to have changed to `IntersectDirectMessageParams`.

While this change appears to have properly propagated to examples, this adjustment appears to be missing from the
- [ ] Release notes
- [ ] Changelog
- [ ] Upgrading guide

with the exception of implicitly observing the change in examples using the class between 0.7.0 documentation and 0.8.0 documentation.

Recommendation: add name change to relevant documentation to avoid unexpectedly broken clients on upgrade.

**Comment by Lance-Drane** [comment]
Thanks, this ended up getting added in the v0.7.0 release but I forgot to mention it. I updated all of the release notes, the changelog, and the upgrading guide to accommodate this. I also corrected the code documentation, though this won't be reflected in prior releases.
